### ISSUE TITLE
Word Embeddings

### ISSUE THREAD

**Issue by gayatrivenugopal** [goru001/inltk#20]
Hi, 
     1. Have you extracted the word embeddings for Hindi from the ULMFiT pre-trained model?
     2. Is that code public?
     3. How can we fine-tune the model with our own dataset and extract embeddings from the new model?

Thanks.

**Comment by goru001** [comment]
@gayatrivenugopal Thanks for reaching out!

Yes, I've extracted the word embeddings from ULMFiT Language Model - which I'd trained on whole of Hindi wikipedia. All of the code, trained LM, dataset is open source and is available in [NLP for Hindi](https://github.com/goru001/nlp-for-hindi) repository. You can fine tune the LM for your own dataset, as I'd done for Hindi classification (code available in the above repo under classification folder) and extract embeddings from the fine tuned LM ([code available here](https://github.com/goru001/inltk/blob/master/inltk/inltk.py#L90))

**Comment by goru001** [comment]
I'll close this issue. Feel free to reopen if there's anything. Thanks!

**Comment by gayatrivenugopal** [comment]
Thanks, I'm facing trouble in understanding the structure of the dataset required to train the model and the process of fine-tuning. My requirement is only to create a model (from Wiki data + my own dataset of stories) from which I can extract extract embeddings for a given token. Will try soon and let you know.

**Comment by goru001** [comment]
> create a model (from Wiki data + my own dataset of stories)

Checkout [this notebook](https://github.com/goru001/nlp-for-hindi/blob/master/classification-bbc-news/Hindi_Classification_Model-BBC_Hindi_News_Data.ipynb). Here I'm creating LM from (Wiki data + classifier data). You can replace classifier data with your data.

**Comment by gayatrivenugopal** [comment]
Thanks, will try.
