### ISSUE TITLE
How to do emotion classification? #helprequest

### ISSUE THREAD

**Issue by octalpixel** [goru001/inltk#40]
Hi 
Could you give me some advise on doing emotion classification and sentiment analysis for Tamil ?

**Comment by goru001** [comment]
@octalpixel Checkout [this notebook](https://github.com/goru001/nlp-for-tamil/blob/master/classification/Tamil%20News%20Text%20Classifier%20Three%20Class.ipynb) - you should be able to do sentiment analysis by substituting your sentiment analysis data in place of news classification. 

Feel free to reopen the issue if you have any other questions.
