### ISSUE TITLE
Issue with identify_language function

### ISSUE THREAD

**Issue by Aditdoshi1** [goru001/inltk#46]
identify_language() works properly when an English sentence is passed.
When a Hindi/other language sentences are passed, it produces a Runtime Error.
Here is the basic code: -

from inltk.inltk import identify_language
identify_language("हैलो")

**Note:-** I did try adding reset_language_identifying_models() function, but the error persist.

Traceback: -
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-d7eabc41ce14> in <module>
      1 from inltk.inltk import identify_language
      2 
----> 3 identify_language("हैलो")

C:\ProgramData\Anaconda3\lib\site-packages\inltk\inltk.py in identify_language(input)
     66     loop = asyncio.get_event_loop()
     67     tasks = [asyncio.ensure_future(check_all_languages_identifying_model())]
---> 68     done = loop.run_until_complete(asyncio.gather(*tasks))[0]
     69     loop.close()
     70     defaults.device = torch.device('cpu')

C:\ProgramData\Anaconda3\lib\asyncio\base_events.py in run_until_complete(self, future)
    568         future.add_done_callback(_run_until_complete_cb)
    569         try:
--> 570             self.run_forever()
    571         except:
    572             if new_task and future.done() and not future.cancelled():

C:\ProgramData\Anaconda3\lib\asyncio\base_events.py in run_forever(self)
    523         self._check_closed()
    524         if self.is_running():
--> 525             raise RuntimeError('This event loop is already running')
    526         if events._get_running_loop() is not None:
    527             raise RuntimeError(

RuntimeError: This event loop is already running

**Comment by balachandragv** [comment]
I faced the same issue and is resolved by installing pytorch 1.3.1 (try conda install pytorch==1.3.1 -c pytorch)

**Comment by tinasoni112** [comment]
text='श्रीमान जी , आपके यहां आज 1 जनवरी से लेकर 6 जन'
identify_language(text)

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-11-afb922e51b3c> in <module>
      1 text='श्रीमान जी , आपके यहां आज 1 जनवरी से लेकर 6 जन'
----> 2 identify_language(text)

D:\Softwares\Anaconda3\lib\site-packages\inltk\inltk.py in identify_language(input)
     66     loop = asyncio.get_event_loop()
     67     tasks = [asyncio.ensure_future(check_all_languages_identifying_model())]
---> 68     done = loop.run_until_complete(asyncio.gather(*tasks))[0]
     69     loop.close()
     70     defaults.device = torch.device('cpu')

D:\Softwares\Anaconda3\lib\asyncio\base_events.py in run_until_complete(self, future)
    569         future.add_done_callback(_run_until_complete_cb)
    570         try:
--> 571             self.run_forever()
    572         except:
    573             if new_task and future.done() and not future.cancelled():

D:\Softwares\Anaconda3\lib\asyncio\base_events.py in run_forever(self)
    524         self._check_closed()
    525         if self.is_running():
--> 526             raise RuntimeError('This event loop is already running')
    527         if events._get_running_loop() is not None:
    528             raise RuntimeError(

RuntimeError: This event loop is already running

**Comment by tinasoni112** [comment]
Facing above issue, and pytorch version is 1.3.1.

**Comment by goru001** [comment]
@tinasoni112 I've seen this happening in jupyter-notebooks. If you run this from python terminal it works fine.  Can you confirm this?

**Comment by goru001** [comment]
Closing this for now. Feel free to reopen if you still need help.
