### ISSUE TITLE
Kernel keeps dying while calling identify_language from inltk.inltk

### ISSUE THREAD

**Issue by balachandragv** [goru001/inltk#48]
This is the result from terminal. I have also tried reset_language_identifying_model but the error still persist. Any ideas?

[I 07:51:21.811 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
kernel 78f77a3b-e8c3-4590-9e4e-58f637292b46 restarted
terminate called after throwing an instance of 'std::runtime_error'
  what():  generic_type: cannot initialize type "WorkerId": an object with that name is already defined

**Comment by goru001** [comment]
@balachandragv This doesn't look like an issue with inltk library. Can you check if you have sufficient RAM while you're running this? Can you also monitor CPU usage etc.

**Comment by balachandragv** [comment]
Hey Gourav.. thanks for your response. My PC has 32 GB of RAM and all cores are not occupied. There were no other kernels running at the time. Tried to check online as well but couldn't find any reason. If I remove the inltk lines of code, it works without any issues. I have set up the language models without any issues.

**Comment by goru001** [comment]
@balachandragv Were you able to resolve this? Sorry I missed notifications for this. If you were still not able to resolve this, it'll be great if you can help me reproduce this error, I'll then be able to help out.

**Comment by goru001** [comment]
Closing this for now. Feel free to reopen if you still face this.
