### ISSUE TITLE
Getting error while using get_sentence_similarity 

### ISSUE THREAD

**Issue by arijitatiitkgp** [goru001/inltk#51]
I'm trying to get similar bengali sentences for a given sentence,but when use the code
from inltk.inltk import get_similar_sentences
get_similar_sentences(sentence, no_of_variants, '<code-of-language>', degree_of_aug = 0.1)

getting error: "torch.nn.modules.module.ModuleAttributeError: 'LSTM' object has no attribute '_flat_weights_names'"

**Comment by dragonsan17** [comment]
Hi @arijitatiitkgp ! How did you resolve this?
