### ISSUE TITLE
Methods other than tokenize like predict n words, similar sentences are not working in inltk

### ISSUE THREAD

**Issue by vermaprashant1** [goru001/inltk#53]
It gives
ModuleAttributeError: 'LSTM' object has no attribute '_flat_weights_names'

**Comment by goru001** [comment]
@vermaprashant1 Is your torch version correct? I think your torch version is >=1.4 which is causing this issue. iNLTK has a dependency on torch v1.3. Checkout [installation instructions here](https://inltk.readthedocs.io/en/latest/api_docs.html#installation)

**Comment by goru001** [comment]
@vermaprashant1 Closing this issue for now as it looks like a dependency issue. Feel free to reopen if there's anything. Thanks!
