### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by kanodiaayush** [goru001/inltk#61]
Hi, I just installed this and tried the following 

```
from inltk.inltk import setup
setup('hi')

from inltk.inltk import get_embedding_vectors
vectors = get_embedding_vectors(example_sent, 'hi')
```

This results in a segmentation fault. Can I get an idea on how to debug this?

**Comment by goru001** [comment]
@kanodiaayush Thanks for reaching out. Are library versions and dependencies in your environment correct? (mainly pytorch)

**Comment by goru001** [comment]
Closing this issue for now, Feel free to re-open if there's anything else. Thanks!
