### ISSUE TITLE
Torch 1.3 installation Issue

### ISSUE THREAD

**Issue by purnasai** [goru001/inltk#62]
Hi, Thanks for the Amazing Library to work in Indic languages. I got an error while Installing torch 1.3. I followed the Installation instructions from [here](https://inltk.readthedocs.io/en/latest/api_docs.html#installation). Error below
`pip install torch==1.3.1+cpu -f https://download.pytorch.org/whl/torch_stable.html`

`Looking in links: https://download.pytorch.org/whl/torch_stable.html`
`ERROR: Could not find a version that satisfies the requirement torch==1.3.1+cpu (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2, 1.4.0, 1.4.0+cpu, 1.4.0+cu100, 1.4.0+cu92, 1.5.0, 1.5.0+cpu, 1.5.0+cu101, 1.5.0+cu92, 1.5.1, 1.5.1+cpu, 1.5.1+cu101, 1.5.1+cu92, 1.6.0, 1.6.0+cpu, 1.6.0+cu101, 1.6.0+cu92, 1.7.0, 1.7.0+cpu, 1.7.0+cu101, 1.7.0+cu110, 1.7.0+cu92, 1.7.1, 1.7.1+cpu, 1.7.1+cu101, 1.7.1+cu110, 1.7.1+cu92)`
`ERROR: No matching distribution found for torch==1.3.1+cpu`

**Comment by goru001** [comment]
Thanks @purnasai for reaching out. I tried installing on colab using the exact same command, and it works as expected, as you can [see here](https://colab.research.google.com/drive/17iDMU3dzsXxgkQag-SkqSPRNy2ZheCgh?usp=sharing). Maybe there's something wrong with the package manager on your system?

**Comment by purnasai** [comment]
I have python3.8 in my system. looks like torch 1.3 requires python3.7 or before versions. Will try them with creating virtual env. Thank you
