### ISSUE TITLE
from inltk.inltk import setup setup('hi') raises error

### ISSUE THREAD

**Issue by DingZengQiang** [goru001/inltk#63]
How to deal with aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host www.dropbox.com:443 ssl:default [Connect call failed ('192.133.77.191', 443)]

**Comment by goru001** [comment]
Thanks @DingZengQiang for reaching out. It seems to be working fine on colab. Can you confirm this? If yes then it might be an issue specific to your network?

**Comment by DingZengQiang** [comment]
> Thanks @DingZengQiang for reaching out. It seems to be working fine on colab. Can you confirm this? If yes then it might be an issue specific to your network?

Thanks for reply! I also think the problem is my network. Now I am considering using proxies, but don't know where to set.

**Comment by goru001** [comment]
Hope you were able to resolve the issue @DingZengQiang . Closing this issue for now as it isn't specific to the library. Feel free to reopen if there's anything else.
