### ISSUE TITLE
Torch throwing an error for all languages other than mixed language

### ISSUE THREAD

**Issue by parthchamp** [goru001/inltk#65]
**torch.nn.modules.module.ModuleAttributeError: 'LSTM' object has no attribute '_flat_weights_names'** error occuring while using Native languages but working fine for mixed languages

**Comment by goru001** [comment]
Thanks @parthchamp for reaching out. It seems your pytorch version is incompatible. You need torch==1.3.1 but likely your torch version is >=1.4

**Comment by parthchamp** [comment]
Thanks @goru001 man for your prompt reply...and ya its working  after installing torch 1.3.1 version
