### ISSUE TITLE
Pytorch 1.3 not available to download

### ISSUE THREAD

**Issue by vaibhav6269** [goru001/inltk#67]
Hi.
PyTorch 1.3 is no longer available to download.
Can you please upgrade the models or suggest how should we use them now?

**Comment by goru001** [comment]
Thanks @vaibhav6269 for reaching out. I was able to install torch on colab by following steps as documented [here](https://inltk.readthedocs.io/en/latest/api_docs.html#installation). Torch wheels are available [here to download](https://download.pytorch.org/whl/torch_stable.html). Let me know if you still face any issues.

**Comment by goru001** [comment]
Closing this issue for now. Feel free to reopen if there's anything else. Thanks!

**Comment by nikhilkmr300** [comment]
If `pip` gives trouble and you don't want to install from the wheels, you could use `conda`. The following still works:

```
conda install pytorch==1.3.0 -c pytorch
```

Refer: [Previous PyTorch Versions](https://pytorch.org/get-started/previous-versions/)
