### ISSUE TITLE
Breaks with PyTorch==1.8.0

### ISSUE THREAD

**Issue by nikhilkmr300** [goru001/inltk#70]
When I try to use the function `get_embedding_vectors`, I get the following error when I use PyTorch v1.8.0:
'LSTM' object has no attribute '_flat_weights_names'. 

Somewhere along the release history, PyTorch might have removed this attribute. I've solved the issue temporarily by installing PyTorch v1.3.0 on `conda` and it works now, but a permanent fix would be nice.

Thanks!

**Comment by nikhilkmr300** [comment]
Sorry, found this right now in closed issues: https://github.com/goru001/inltk/issues/67.

**Comment by djsethi09** [comment]
Hello @nikhilkmr300 Please what is the solution that worked for you?
I get this error with pytorch 1.8.1
'LSTM' object has no attribute '_flat_weights_names

**Comment by nikhilkmr300** [comment]
Downgrading the version of PyTorch to 1.3 worked.

I used `conda` with the following command if I recall correctly (refer [this](https://pytorch.org/get-started/previous-versions/#v120)):
```
conda install pytorch==1.3.0
```

The [iNLTK docs](https://inltk.readthedocs.io/en/latest/api_docs.html) provide a solution if you're using `pip`.
