### ISSUE TITLE
get_similar_vectors, get_similar_sentences fails with AttributeError: 'LSTM' object has no attribute '_flat_weights_names'

### ISSUE THREAD

**Issue by jayaBalaR** [goru001/inltk#79]
I have installed inltk using the following on collaborator run on normal CPU as hardware accelerator. These work fine
![image](https://user-images.githubusercontent.com/21074002/132837592-b27d8401-1b14-4a4e-bd03-88d013354812.png)

But while using the function calls get_similar_vectors or get_similar_sentences it fails
![image](https://user-images.githubusercontent.com/21074002/132837795-e6450c9d-990c-495d-89cc-90c2cd50e236.png)
![image](https://user-images.githubusercontent.com/21074002/132837880-0c0a9de7-6510-49a6-8d59-13eb6c279b09.png)

I have used these functions around 4 months back and it was working fine. Not sure if some code got updated.Could you please look into this and provide a resolution
Thank you
Jayabalambika.R

**Comment by goru001** [comment]
Hi @jayaBalaR , can you double check if you're using the correct torch version? It seems your torch version is >= 1.4

**Comment by jayaBalaR** [comment]
@goru001  thanks after reverting torch version to less than 1.9 , it works. Hence issue can be closed

**Comment by Onkar-2803** [comment]
Have executed the [collab notebook](https://colab.research.google.com/drive/17iDMU3dzsXxgkQag-SkqSPRNy2ZheCgh?usp=sharing#scrollTo=kDV3PBgq-PuJ) provided by you, I'm still getting the same error.
