### ISSUE TITLE
Dimensionality Reduction

### ISSUE THREAD

**Issue by RAJAN8553** [goru001/inltk#81]
Yes now i understood Thank you @goru001.
Can I tweak that hyperparameter as i need less dimensional or I have to apply feature extraction method.
Can you suggest good feature extraction method for your model. 

Should I reduce the dimension of the data(as the model is giving out 400 vectors for a single sentence). Size of my data is 600(rows, Gujarati language) and after getting 400 vectors for each sentence the total size will be 600x400 which is a huge data to handle.

**Comment by goru001** [comment]
Hi @RAJAN8553 , you can reduce the dimensionality using [PCA](https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.PCA.html) or similar algos.

**Comment by goru001** [comment]
Closing this issue for now. Feel free to reopen if there's anything else. Thanks!
