### ISSUE TITLE
[Documentation Typo] The order of installation in official documentation is wrong

### ISSUE THREAD

**Issue by sara-02** [goru001/inltk#85]
In the installation [section](https://inltk.readthedocs.io/en/latest/api_docs.html#installation), the torch install step is mentioned first, but when inltk installs after this, it replaces the required torch version which leads to the `LSTM` error due to depreciation.
Suggest we fix the order to inltk, followed by torch uninstall and then the torch 1.3 install step.

**Comment by nitesh18400** [comment]
Can I work on this issue? I recently encountered this error.

**Comment by DraymondHIT** [comment]
`!pip install inltk
!pip install torch==1.3.1+cpu -f https://download.pytorch.org/whl/torch_stable.html`
This order is ok.

**Comment by nitesh18400** [comment]
@DraymondHIT Yes, the correct order should be this.

**Comment by goru001** [comment]
Thanks everyone for pointing this out. @nitesh18400 Please feel free to raise a PR. It should be a small change [here](https://github.com/goru001/inltk/blob/master/docs/api_docs.md)

**Comment by goru001** [comment]
Thanks @nitesh18400 for raising the PR. I've merged the PR and hence closing this issue. Thanks everyone!
